application: unscramble-app
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon(.*)
  static_files: static/apple-touch-icon\1
  upload: static/apple-touch-icon.*

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /.*
  script: _go_app
